# source: https://pre-commit.com/
# repos:
#     - repo: meta
#       hook:
#           - id: identity

#     - repo: https://github.com/pre-commit/pre-commit-hooks
#       rev: v4.4.0
#       hooks:
#          - id: check_merge-conflict
#          - id: check-added-large-files
#          - id: end-of-file-fixer
#          - id: trailing-whitespace
#          - id: check-added-large-files
#          - id: check-yaml
#            args:
#                - --unsafe
#          - id: name-tests-test
#            args: [--pytest-test-first]
#          - id: detect-private-key

#       # - repo: https://github.com/pre-commit/pygrep-hooks
#     - repo: https://github.com/psf/black
#       rev: 22.10.0
#       hooks:
#       -   id: black

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
